services:
  api_demo:
    image: hienle2004/coin-price-be-go-demo
    depends_on:
      - db_demo
    build:  ./backend
    ports:
      - 8080:8080
    # env_file:
    #   - .env
    restart: unless-stopped
    labels: 
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      DB_URL: mongodb://db_demo/coin-price
    develop:
      watch:
        - path: ./backend/go.mod
          action: rebuild
        - path: ./backend
          target: /app
          action: sync
  db_demo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - coin-price:/data/db_demo

volumes:
  coin-price: