// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Ngoc Hien",
            "url": "https://github.com/HienLe2004/coin-price-be-go-demo"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/funding-rate": {
            "get": {
                "description": "get funding-rate by symbol",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "funding-rate"
                ],
                "summary": "Show a funding-rate",
                "parameters": [
                    {
                        "type": "string",
                        "description": "symbol of funding rate",
                        "name": "symbol",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseFundingRate"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.ResponseFundingRate": {
            "type": "object",
            "properties": {
                "adjustedFundingRateCap": {
                    "type": "string"
                },
                "adjustedFundingRateFloor": {
                    "type": "string"
                },
                "eventTime": {
                    "type": "string"
                },
                "fundingCountDown": {
                    "type": "string"
                },
                "fundingIntervalHours": {
                    "type": "integer"
                },
                "fundingRate": {
                    "type": "string"
                },
                "symbol": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Demo Documenting API",
	Description:      "coin price go backend",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
