name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    environment: dev
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build and push the Docker image
      run: |
        echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_ACCESS_USER }}" --password-stdin
        docker build -t hienle2004/coin-price-be-go-demo .
        docker push hienle2004/coin-price-be-go-demo
    - name: Remove Docker image
      run: |
        docker rmi hienle2004/coin-price-be-go-demo
    - name: Deploy on VPS
      run: |
        sshpass -p ${{ secrets.VPS_PASSWORD }} ssh -o StrictHostKeyChecking=no root@${{ secrets.VPS_IP }} "
          cd server
          
          echo 'y' | sudo docker container prune
          sudo docker rmi $(docker images -a -q) 2>dev>null || true  
          sudo docker compose down
          sudo docker compose pull

          sudo docker compose up
        "
