# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
    paths-ignore: 
      - 'docs/**'
      - 'reports/**'
      - '*.md'
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build Docker Image
      working-directory: backend
      run: docker build -t hienle2004/coin-price-be-go-demo:${{github.sha}} .

    - name: Test
      working-directory: backend
      run: go test -v ./...

    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u hienle2004 --password-stdin

    - name: Push Docker Image
      run: docker push hienle2004/coin-price-be-go-demo:${{github.sha}}
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker
      uses: actions/setup-docker@v2
    - name: Deploy
      run: docker-compose -f docker-compose.yml up --build -d
